### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by lepmik** [CINPLA/CA2_MEC#2]
- [ ] @sarahthon upload latest notebooks, delete those that are not used
- [ ] Konvertere til NWB (notebooks/ratemap.maria.ipynb, notebooks/show-me-ratemaps.ipynb, notebooks/neural-population-decoder.ipynb, notebooks/show-me-spikes-and-tracking.ipynb)
- [ ] Endre navn på notebooks/ratemap.maria.ipynb, notebooks/show-me-ratemaps.ipynb, notebooks/show-me-spikes-and-tracking.ipynb
- [ ]  notebooks/ratemap.maria.ipynb legge til hoderetning
- [ ] Calculate statistics fra septum_mec_novel (notebooks/10_calculate_spatial_statistics.ipynb)
- [ ] Neural population decoding - trial decoding bug, hjelp fra Vemund?
- [ ] Lagre statistikk og data i csv

**Comment by lepmik** [comment]
priorities:
 - identify neurons
 - notebooks/ratemap.maria.ipynb
 - notebooks/show-me-ratemaps.ipynb
